#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_TRACUU.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Rent_Office")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertViTri(ViTri instance);
    partial void UpdateViTri(ViTri instance);
    partial void DeleteViTri(ViTri instance);
    partial void InsertHinhThuc(HinhThuc instance);
    partial void UpdateHinhThuc(HinhThuc instance);
    partial void DeleteHinhThuc(HinhThuc instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertNguoiLH(NguoiLH instance);
    partial void UpdateNguoiLH(NguoiLH instance);
    partial void DeleteNguoiLH(NguoiLH instance);
    partial void InsertPhanLoaiThue(PhanLoaiThue instance);
    partial void UpdatePhanLoaiThue(PhanLoaiThue instance);
    partial void DeletePhanLoaiThue(PhanLoaiThue instance);
    partial void InsertQuan(Quan instance);
    partial void UpdateQuan(Quan instance);
    partial void DeleteQuan(Quan instance);
    partial void InsertTheoDoi(TheoDoi instance);
    partial void UpdateTheoDoi(TheoDoi instance);
    partial void DeleteTheoDoi(TheoDoi instance);
    partial void InsertVanPhong(VanPhong instance);
    partial void UpdateVanPhong(VanPhong instance);
    partial void DeleteVanPhong(VanPhong instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Rent_OfficeConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Anh_CT_VP> Anh_CT_VPs
		{
			get
			{
				return this.GetTable<Anh_CT_VP>();
			}
		}
		
		public System.Data.Linq.Table<ViTri> ViTris
		{
			get
			{
				return this.GetTable<ViTri>();
			}
		}
		
		public System.Data.Linq.Table<HinhThuc> HinhThucs
		{
			get
			{
				return this.GetTable<HinhThuc>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<NguoiLH> NguoiLHs
		{
			get
			{
				return this.GetTable<NguoiLH>();
			}
		}
		
		public System.Data.Linq.Table<PhanLoaiThue> PhanLoaiThues
		{
			get
			{
				return this.GetTable<PhanLoaiThue>();
			}
		}
		
		public System.Data.Linq.Table<Quan> Quans
		{
			get
			{
				return this.GetTable<Quan>();
			}
		}
		
		public System.Data.Linq.Table<TheoDoi> TheoDois
		{
			get
			{
				return this.GetTable<TheoDoi>();
			}
		}
		
		public System.Data.Linq.Table<VanPhong> VanPhongs
		{
			get
			{
				return this.GetTable<VanPhong>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fChuyenCoDauThanhKhongDau", IsComposable=true)]
		public string fChuyenCoDauThanhKhongDau([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string inputVar)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inputVar).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Vp_Da_Theo_doi", IsComposable=true)]
		public IQueryable<Vp_Da_Theo_doiResult> Vp_Da_Theo_doi([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> maKh)
		{
			return this.CreateMethodCallQuery<Vp_Da_Theo_doiResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKh);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Anh_CT_VP")]
	public partial class Anh_CT_VP
	{
		
		private string _MaVP;
		
		private string _AnhCT;
		
		private string _Title;
		
		public Anh_CT_VP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVP", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaVP
		{
			get
			{
				return this._MaVP;
			}
			set
			{
				if ((this._MaVP != value))
				{
					this._MaVP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhCT", DbType="VarChar(200)")]
		public string AnhCT
		{
			get
			{
				return this._AnhCT;
			}
			set
			{
				if ((this._AnhCT != value))
				{
					this._AnhCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViTri")]
	public partial class ViTri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaViTri;
		
		private string _TenViTri;
		
		private EntitySet<VanPhong> _VanPhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaViTriChanging(int value);
    partial void OnMaViTriChanged();
    partial void OnTenViTriChanging(string value);
    partial void OnTenViTriChanged();
    #endregion
		
		public ViTri()
		{
			this._VanPhongs = new EntitySet<VanPhong>(new Action<VanPhong>(this.attach_VanPhongs), new Action<VanPhong>(this.detach_VanPhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaViTri", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaViTri
		{
			get
			{
				return this._MaViTri;
			}
			set
			{
				if ((this._MaViTri != value))
				{
					this.OnMaViTriChanging(value);
					this.SendPropertyChanging();
					this._MaViTri = value;
					this.SendPropertyChanged("MaViTri");
					this.OnMaViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenViTri", DbType="NVarChar(50)")]
		public string TenViTri
		{
			get
			{
				return this._TenViTri;
			}
			set
			{
				if ((this._TenViTri != value))
				{
					this.OnTenViTriChanging(value);
					this.SendPropertyChanging();
					this._TenViTri = value;
					this.SendPropertyChanged("TenViTri");
					this.OnTenViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ViTri_VanPhong", Storage="_VanPhongs", ThisKey="MaViTri", OtherKey="MaViTri")]
		public EntitySet<VanPhong> VanPhongs
		{
			get
			{
				return this._VanPhongs;
			}
			set
			{
				this._VanPhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VanPhongs(VanPhong entity)
		{
			this.SendPropertyChanging();
			entity.ViTri = this;
		}
		
		private void detach_VanPhongs(VanPhong entity)
		{
			this.SendPropertyChanging();
			entity.ViTri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HinhThuc")]
	public partial class HinhThuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHinhThuc;
		
		private string _TenHinhThuc;
		
		private EntitySet<VanPhong> _VanPhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHinhThucChanging(int value);
    partial void OnMaHinhThucChanged();
    partial void OnTenHinhThucChanging(string value);
    partial void OnTenHinhThucChanged();
    #endregion
		
		public HinhThuc()
		{
			this._VanPhongs = new EntitySet<VanPhong>(new Action<VanPhong>(this.attach_VanPhongs), new Action<VanPhong>(this.detach_VanPhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHinhThuc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHinhThuc
		{
			get
			{
				return this._MaHinhThuc;
			}
			set
			{
				if ((this._MaHinhThuc != value))
				{
					this.OnMaHinhThucChanging(value);
					this.SendPropertyChanging();
					this._MaHinhThuc = value;
					this.SendPropertyChanged("MaHinhThuc");
					this.OnMaHinhThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHinhThuc", DbType="NVarChar(50)")]
		public string TenHinhThuc
		{
			get
			{
				return this._TenHinhThuc;
			}
			set
			{
				if ((this._TenHinhThuc != value))
				{
					this.OnTenHinhThucChanging(value);
					this.SendPropertyChanging();
					this._TenHinhThuc = value;
					this.SendPropertyChanged("TenHinhThuc");
					this.OnTenHinhThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HinhThuc_VanPhong", Storage="_VanPhongs", ThisKey="MaHinhThuc", OtherKey="MaHinhThuc")]
		public EntitySet<VanPhong> VanPhongs
		{
			get
			{
				return this._VanPhongs;
			}
			set
			{
				this._VanPhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VanPhongs(VanPhong entity)
		{
			this.SendPropertyChanging();
			entity.HinhThuc = this;
		}
		
		private void detach_VanPhongs(VanPhong entity)
		{
			this.SendPropertyChanging();
			entity.HinhThuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _MaKH;
		
		private string _TenKH;
		
		private string _CoQuan;
		
		private string _DiaChi;
		
		private string _SoDT;
		
		private string _Email;
		
		private string _CMND;
		
		private string _Username;
		
		private string _Pass;
		
		private System.Nullable<bool> _FlagActive;
		
		private System.Nullable<bool> _Admin;
		
		private EntitySet<TheoDoi> _TheoDois;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(System.Guid value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnCoQuanChanging(string value);
    partial void OnCoQuanChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnFlagActiveChanging(System.Nullable<bool> value);
    partial void OnFlagActiveChanged();
    partial void OnAdminChanging(System.Nullable<bool> value);
    partial void OnAdminChanged();
    #endregion
		
		public KhachHang()
		{
			this._TheoDois = new EntitySet<TheoDoi>(new Action<TheoDoi>(this.attach_TheoDois), new Action<TheoDoi>(this.detach_TheoDois));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoQuan", DbType="NVarChar(50)")]
		public string CoQuan
		{
			get
			{
				return this._CoQuan;
			}
			set
			{
				if ((this._CoQuan != value))
				{
					this.OnCoQuanChanging(value);
					this.SendPropertyChanging();
					this._CoQuan = value;
					this.SendPropertyChanged("CoQuan");
					this.OnCoQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="VarChar(12)")]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(12)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="VarChar(50)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagActive", DbType="Bit")]
		public System.Nullable<bool> FlagActive
		{
			get
			{
				return this._FlagActive;
			}
			set
			{
				if ((this._FlagActive != value))
				{
					this.OnFlagActiveChanging(value);
					this.SendPropertyChanging();
					this._FlagActive = value;
					this.SendPropertyChanged("FlagActive");
					this.OnFlagActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin", DbType="Bit")]
		public System.Nullable<bool> Admin
		{
			get
			{
				return this._Admin;
			}
			set
			{
				if ((this._Admin != value))
				{
					this.OnAdminChanging(value);
					this.SendPropertyChanging();
					this._Admin = value;
					this.SendPropertyChanged("Admin");
					this.OnAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_TheoDoi", Storage="_TheoDois", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<TheoDoi> TheoDois
		{
			get
			{
				return this._TheoDois;
			}
			set
			{
				this._TheoDois.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TheoDois(TheoDoi entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_TheoDois(TheoDoi entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiLH")]
	public partial class NguoiLH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguoiLH;
		
		private string _TenNguoiLH;
		
		private string _Anh;
		
		private string _SoDT;
		
		private string _Email;
		
		private string _MoTa;
		
		private EntitySet<VanPhong> _VanPhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiLHChanging(string value);
    partial void OnMaNguoiLHChanged();
    partial void OnTenNguoiLHChanging(string value);
    partial void OnTenNguoiLHChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public NguoiLH()
		{
			this._VanPhongs = new EntitySet<VanPhong>(new Action<VanPhong>(this.attach_VanPhongs), new Action<VanPhong>(this.detach_VanPhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiLH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiLH
		{
			get
			{
				return this._MaNguoiLH;
			}
			set
			{
				if ((this._MaNguoiLH != value))
				{
					this.OnMaNguoiLHChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiLH = value;
					this.SendPropertyChanged("MaNguoiLH");
					this.OnMaNguoiLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiLH", DbType="NVarChar(50)")]
		public string TenNguoiLH
		{
			get
			{
				return this._TenNguoiLH;
			}
			set
			{
				if ((this._TenNguoiLH != value))
				{
					this.OnTenNguoiLHChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiLH = value;
					this.SendPropertyChanged("TenNguoiLH");
					this.OnTenNguoiLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="VarChar(MAX)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="VarChar(12)")]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiLH_VanPhong", Storage="_VanPhongs", ThisKey="MaNguoiLH", OtherKey="MaNguoiLH")]
		public EntitySet<VanPhong> VanPhongs
		{
			get
			{
				return this._VanPhongs;
			}
			set
			{
				this._VanPhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VanPhongs(VanPhong entity)
		{
			this.SendPropertyChanging();
			entity.NguoiLH = this;
		}
		
		private void detach_VanPhongs(VanPhong entity)
		{
			this.SendPropertyChanging();
			entity.NguoiLH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanLoaiThue")]
	public partial class PhanLoaiThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoai;
		
		private string _TenLoai;
		
		private EntitySet<VanPhong> _VanPhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(int value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public PhanLoaiThue()
		{
			this._VanPhongs = new EntitySet<VanPhong>(new Action<VanPhong>(this.attach_VanPhongs), new Action<VanPhong>(this.detach_VanPhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanLoaiThue_VanPhong", Storage="_VanPhongs", ThisKey="MaLoai", OtherKey="MaPLThue")]
		public EntitySet<VanPhong> VanPhongs
		{
			get
			{
				return this._VanPhongs;
			}
			set
			{
				this._VanPhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VanPhongs(VanPhong entity)
		{
			this.SendPropertyChanging();
			entity.PhanLoaiThue = this;
		}
		
		private void detach_VanPhongs(VanPhong entity)
		{
			this.SendPropertyChanging();
			entity.PhanLoaiThue = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Quan")]
	public partial class Quan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaQuan;
		
		private string _TenQuan;
		
		private EntitySet<VanPhong> _VanPhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQuanChanging(int value);
    partial void OnMaQuanChanged();
    partial void OnTenQuanChanging(string value);
    partial void OnTenQuanChanged();
    #endregion
		
		public Quan()
		{
			this._VanPhongs = new EntitySet<VanPhong>(new Action<VanPhong>(this.attach_VanPhongs), new Action<VanPhong>(this.detach_VanPhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaQuan
		{
			get
			{
				return this._MaQuan;
			}
			set
			{
				if ((this._MaQuan != value))
				{
					this.OnMaQuanChanging(value);
					this.SendPropertyChanging();
					this._MaQuan = value;
					this.SendPropertyChanged("MaQuan");
					this.OnMaQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuan", DbType="NVarChar(50)")]
		public string TenQuan
		{
			get
			{
				return this._TenQuan;
			}
			set
			{
				if ((this._TenQuan != value))
				{
					this.OnTenQuanChanging(value);
					this.SendPropertyChanging();
					this._TenQuan = value;
					this.SendPropertyChanged("TenQuan");
					this.OnTenQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Quan_VanPhong", Storage="_VanPhongs", ThisKey="MaQuan", OtherKey="MaQuan")]
		public EntitySet<VanPhong> VanPhongs
		{
			get
			{
				return this._VanPhongs;
			}
			set
			{
				this._VanPhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VanPhongs(VanPhong entity)
		{
			this.SendPropertyChanging();
			entity.Quan = this;
		}
		
		private void detach_VanPhongs(VanPhong entity)
		{
			this.SendPropertyChanging();
			entity.Quan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheoDoi")]
	public partial class TheoDoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _MaKH;
		
		private string _MaVP;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<VanPhong> _VanPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(System.Guid value);
    partial void OnMaKHChanged();
    partial void OnMaVPChanging(string value);
    partial void OnMaVPChanged();
    #endregion
		
		public TheoDoi()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._VanPhong = default(EntityRef<VanPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVP", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaVP
		{
			get
			{
				return this._MaVP;
			}
			set
			{
				if ((this._MaVP != value))
				{
					if (this._VanPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaVPChanging(value);
					this.SendPropertyChanging();
					this._MaVP = value;
					this.SendPropertyChanged("MaVP");
					this.OnMaVPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_TheoDoi", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.TheoDois.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.TheoDois.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(System.Guid);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VanPhong_TheoDoi", Storage="_VanPhong", ThisKey="MaVP", OtherKey="MaVP", IsForeignKey=true)]
		public VanPhong VanPhong
		{
			get
			{
				return this._VanPhong.Entity;
			}
			set
			{
				VanPhong previousValue = this._VanPhong.Entity;
				if (((previousValue != value) 
							|| (this._VanPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VanPhong.Entity = null;
						previousValue.TheoDois.Remove(this);
					}
					this._VanPhong.Entity = value;
					if ((value != null))
					{
						value.TheoDois.Add(this);
						this._MaVP = value.MaVP;
					}
					else
					{
						this._MaVP = default(string);
					}
					this.SendPropertyChanged("VanPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VanPhong")]
	public partial class VanPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaVP;
		
		private string _TenVP;
		
		private string _SoNha;
		
		private System.Nullable<int> _MaQuan;
		
		private System.Nullable<decimal> _DienTich;
		
		private System.Nullable<decimal> _Gia;
		
		private string _MoTa;
		
		private string _BanDo;
		
		private string _MaNguoiLH;
		
		private System.Nullable<int> _MaPLThue;
		
		private System.Nullable<int> _MaViTri;
		
		private System.Nullable<int> _MaHinhThuc;
		
		private System.Nullable<decimal> _LuotView;
		
		private string _Avarta;
		
		private EntitySet<TheoDoi> _TheoDois;
		
		private EntityRef<HinhThuc> _HinhThuc;
		
		private EntityRef<NguoiLH> _NguoiLH;
		
		private EntityRef<PhanLoaiThue> _PhanLoaiThue;
		
		private EntityRef<Quan> _Quan;
		
		private EntityRef<ViTri> _ViTri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaVPChanging(string value);
    partial void OnMaVPChanged();
    partial void OnTenVPChanging(string value);
    partial void OnTenVPChanged();
    partial void OnSoNhaChanging(string value);
    partial void OnSoNhaChanged();
    partial void OnMaQuanChanging(System.Nullable<int> value);
    partial void OnMaQuanChanged();
    partial void OnDienTichChanging(System.Nullable<decimal> value);
    partial void OnDienTichChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnBanDoChanging(string value);
    partial void OnBanDoChanged();
    partial void OnMaNguoiLHChanging(string value);
    partial void OnMaNguoiLHChanged();
    partial void OnMaPLThueChanging(System.Nullable<int> value);
    partial void OnMaPLThueChanged();
    partial void OnMaViTriChanging(System.Nullable<int> value);
    partial void OnMaViTriChanged();
    partial void OnMaHinhThucChanging(System.Nullable<int> value);
    partial void OnMaHinhThucChanged();
    partial void OnLuotViewChanging(System.Nullable<decimal> value);
    partial void OnLuotViewChanged();
    partial void OnAvartaChanging(string value);
    partial void OnAvartaChanged();
    #endregion
		
		public VanPhong()
		{
			this._TheoDois = new EntitySet<TheoDoi>(new Action<TheoDoi>(this.attach_TheoDois), new Action<TheoDoi>(this.detach_TheoDois));
			this._HinhThuc = default(EntityRef<HinhThuc>);
			this._NguoiLH = default(EntityRef<NguoiLH>);
			this._PhanLoaiThue = default(EntityRef<PhanLoaiThue>);
			this._Quan = default(EntityRef<Quan>);
			this._ViTri = default(EntityRef<ViTri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVP", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaVP
		{
			get
			{
				return this._MaVP;
			}
			set
			{
				if ((this._MaVP != value))
				{
					this.OnMaVPChanging(value);
					this.SendPropertyChanging();
					this._MaVP = value;
					this.SendPropertyChanged("MaVP");
					this.OnMaVPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVP", DbType="NVarChar(50)")]
		public string TenVP
		{
			get
			{
				return this._TenVP;
			}
			set
			{
				if ((this._TenVP != value))
				{
					this.OnTenVPChanging(value);
					this.SendPropertyChanging();
					this._TenVP = value;
					this.SendPropertyChanged("TenVP");
					this.OnTenVPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNha", DbType="NVarChar(50)")]
		public string SoNha
		{
			get
			{
				return this._SoNha;
			}
			set
			{
				if ((this._SoNha != value))
				{
					this.OnSoNhaChanging(value);
					this.SendPropertyChanging();
					this._SoNha = value;
					this.SendPropertyChanged("SoNha");
					this.OnSoNhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuan", DbType="Int")]
		public System.Nullable<int> MaQuan
		{
			get
			{
				return this._MaQuan;
			}
			set
			{
				if ((this._MaQuan != value))
				{
					if (this._Quan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQuanChanging(value);
					this.SendPropertyChanging();
					this._MaQuan = value;
					this.SendPropertyChanged("MaQuan");
					this.OnMaQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this.OnDienTichChanging(value);
					this.SendPropertyChanging();
					this._DienTich = value;
					this.SendPropertyChanged("DienTich");
					this.OnDienTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Money")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BanDo", DbType="NChar(10)")]
		public string BanDo
		{
			get
			{
				return this._BanDo;
			}
			set
			{
				if ((this._BanDo != value))
				{
					this.OnBanDoChanging(value);
					this.SendPropertyChanging();
					this._BanDo = value;
					this.SendPropertyChanged("BanDo");
					this.OnBanDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiLH", DbType="VarChar(10)")]
		public string MaNguoiLH
		{
			get
			{
				return this._MaNguoiLH;
			}
			set
			{
				if ((this._MaNguoiLH != value))
				{
					if (this._NguoiLH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiLHChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiLH = value;
					this.SendPropertyChanged("MaNguoiLH");
					this.OnMaNguoiLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPLThue", DbType="Int")]
		public System.Nullable<int> MaPLThue
		{
			get
			{
				return this._MaPLThue;
			}
			set
			{
				if ((this._MaPLThue != value))
				{
					if (this._PhanLoaiThue.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPLThueChanging(value);
					this.SendPropertyChanging();
					this._MaPLThue = value;
					this.SendPropertyChanged("MaPLThue");
					this.OnMaPLThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaViTri", DbType="Int")]
		public System.Nullable<int> MaViTri
		{
			get
			{
				return this._MaViTri;
			}
			set
			{
				if ((this._MaViTri != value))
				{
					if (this._ViTri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaViTriChanging(value);
					this.SendPropertyChanging();
					this._MaViTri = value;
					this.SendPropertyChanged("MaViTri");
					this.OnMaViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHinhThuc", DbType="Int")]
		public System.Nullable<int> MaHinhThuc
		{
			get
			{
				return this._MaHinhThuc;
			}
			set
			{
				if ((this._MaHinhThuc != value))
				{
					if (this._HinhThuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHinhThucChanging(value);
					this.SendPropertyChanging();
					this._MaHinhThuc = value;
					this.SendPropertyChanged("MaHinhThuc");
					this.OnMaHinhThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotView", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> LuotView
		{
			get
			{
				return this._LuotView;
			}
			set
			{
				if ((this._LuotView != value))
				{
					this.OnLuotViewChanging(value);
					this.SendPropertyChanging();
					this._LuotView = value;
					this.SendPropertyChanged("LuotView");
					this.OnLuotViewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avarta", DbType="VarChar(MAX)")]
		public string Avarta
		{
			get
			{
				return this._Avarta;
			}
			set
			{
				if ((this._Avarta != value))
				{
					this.OnAvartaChanging(value);
					this.SendPropertyChanging();
					this._Avarta = value;
					this.SendPropertyChanged("Avarta");
					this.OnAvartaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VanPhong_TheoDoi", Storage="_TheoDois", ThisKey="MaVP", OtherKey="MaVP")]
		public EntitySet<TheoDoi> TheoDois
		{
			get
			{
				return this._TheoDois;
			}
			set
			{
				this._TheoDois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HinhThuc_VanPhong", Storage="_HinhThuc", ThisKey="MaHinhThuc", OtherKey="MaHinhThuc", IsForeignKey=true)]
		public HinhThuc HinhThuc
		{
			get
			{
				return this._HinhThuc.Entity;
			}
			set
			{
				HinhThuc previousValue = this._HinhThuc.Entity;
				if (((previousValue != value) 
							|| (this._HinhThuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HinhThuc.Entity = null;
						previousValue.VanPhongs.Remove(this);
					}
					this._HinhThuc.Entity = value;
					if ((value != null))
					{
						value.VanPhongs.Add(this);
						this._MaHinhThuc = value.MaHinhThuc;
					}
					else
					{
						this._MaHinhThuc = default(Nullable<int>);
					}
					this.SendPropertyChanged("HinhThuc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiLH_VanPhong", Storage="_NguoiLH", ThisKey="MaNguoiLH", OtherKey="MaNguoiLH", IsForeignKey=true)]
		public NguoiLH NguoiLH
		{
			get
			{
				return this._NguoiLH.Entity;
			}
			set
			{
				NguoiLH previousValue = this._NguoiLH.Entity;
				if (((previousValue != value) 
							|| (this._NguoiLH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiLH.Entity = null;
						previousValue.VanPhongs.Remove(this);
					}
					this._NguoiLH.Entity = value;
					if ((value != null))
					{
						value.VanPhongs.Add(this);
						this._MaNguoiLH = value.MaNguoiLH;
					}
					else
					{
						this._MaNguoiLH = default(string);
					}
					this.SendPropertyChanged("NguoiLH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanLoaiThue_VanPhong", Storage="_PhanLoaiThue", ThisKey="MaPLThue", OtherKey="MaLoai", IsForeignKey=true)]
		public PhanLoaiThue PhanLoaiThue
		{
			get
			{
				return this._PhanLoaiThue.Entity;
			}
			set
			{
				PhanLoaiThue previousValue = this._PhanLoaiThue.Entity;
				if (((previousValue != value) 
							|| (this._PhanLoaiThue.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhanLoaiThue.Entity = null;
						previousValue.VanPhongs.Remove(this);
					}
					this._PhanLoaiThue.Entity = value;
					if ((value != null))
					{
						value.VanPhongs.Add(this);
						this._MaPLThue = value.MaLoai;
					}
					else
					{
						this._MaPLThue = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhanLoaiThue");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Quan_VanPhong", Storage="_Quan", ThisKey="MaQuan", OtherKey="MaQuan", IsForeignKey=true)]
		public Quan Quan
		{
			get
			{
				return this._Quan.Entity;
			}
			set
			{
				Quan previousValue = this._Quan.Entity;
				if (((previousValue != value) 
							|| (this._Quan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Quan.Entity = null;
						previousValue.VanPhongs.Remove(this);
					}
					this._Quan.Entity = value;
					if ((value != null))
					{
						value.VanPhongs.Add(this);
						this._MaQuan = value.MaQuan;
					}
					else
					{
						this._MaQuan = default(Nullable<int>);
					}
					this.SendPropertyChanged("Quan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ViTri_VanPhong", Storage="_ViTri", ThisKey="MaViTri", OtherKey="MaViTri", IsForeignKey=true)]
		public ViTri ViTri
		{
			get
			{
				return this._ViTri.Entity;
			}
			set
			{
				ViTri previousValue = this._ViTri.Entity;
				if (((previousValue != value) 
							|| (this._ViTri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ViTri.Entity = null;
						previousValue.VanPhongs.Remove(this);
					}
					this._ViTri.Entity = value;
					if ((value != null))
					{
						value.VanPhongs.Add(this);
						this._MaViTri = value.MaViTri;
					}
					else
					{
						this._MaViTri = default(Nullable<int>);
					}
					this.SendPropertyChanged("ViTri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TheoDois(TheoDoi entity)
		{
			this.SendPropertyChanging();
			entity.VanPhong = this;
		}
		
		private void detach_TheoDois(TheoDoi entity)
		{
			this.SendPropertyChanging();
			entity.VanPhong = null;
		}
	}
	
	public partial class Vp_Da_Theo_doiResult
	{
		
		private string _MaVP;
		
		private string _TenVP;
		
		private string _SoNha;
		
		private string _MoTa;
		
		private string _Anh;
		
		private System.Nullable<decimal> _DienTich;
		
		private System.Nullable<decimal> _Gia;
		
		public Vp_Da_Theo_doiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVP", DbType="VarChar(10)")]
		public string MaVP
		{
			get
			{
				return this._MaVP;
			}
			set
			{
				if ((this._MaVP != value))
				{
					this._MaVP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVP", DbType="NVarChar(100)")]
		public string TenVP
		{
			get
			{
				return this._TenVP;
			}
			set
			{
				if ((this._TenVP != value))
				{
					this._TenVP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNha", DbType="NVarChar(100)")]
		public string SoNha
		{
			get
			{
				return this._SoNha;
			}
			set
			{
				if ((this._SoNha != value))
				{
					this._SoNha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this._MoTa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="VarChar(MAX)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this._Anh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this._DienTich = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Money")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this._Gia = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
