#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_TRACUU.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BatDongSan")]
	public partial class DataTraCuuVPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAcreage(Acreage instance);
    partial void UpdateAcreage(Acreage instance);
    partial void DeleteAcreage(Acreage instance);
    partial void InsertWard(Ward instance);
    partial void UpdateWard(Ward instance);
    partial void DeleteWard(Ward instance);
    partial void InsertAddress(Address instance);
    partial void UpdateAddress(Address instance);
    partial void DeleteAddress(Address instance);
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertLand(Land instance);
    partial void UpdateLand(Land instance);
    partial void DeleteLand(Land instance);
    partial void InsertStreet(Street instance);
    partial void UpdateStreet(Street instance);
    partial void DeleteStreet(Street instance);
    partial void InsertType_Land(Type_Land instance);
    partial void UpdateType_Land(Type_Land instance);
    partial void DeleteType_Land(Type_Land instance);
    partial void InsertTrouser(Trouser instance);
    partial void UpdateTrouser(Trouser instance);
    partial void DeleteTrouser(Trouser instance);
    #endregion
		
		public DataTraCuuVPDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BatDongSanConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataTraCuuVPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataTraCuuVPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataTraCuuVPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataTraCuuVPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Acreage> Acreages
		{
			get
			{
				return this.GetTable<Acreage>();
			}
		}
		
		public System.Data.Linq.Table<Ward> Wards
		{
			get
			{
				return this.GetTable<Ward>();
			}
		}
		
		public System.Data.Linq.Table<Address> Addresses
		{
			get
			{
				return this.GetTable<Address>();
			}
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<Follow> Follows
		{
			get
			{
				return this.GetTable<Follow>();
			}
		}
		
		public System.Data.Linq.Table<Image_Detail> Image_Details
		{
			get
			{
				return this.GetTable<Image_Detail>();
			}
		}
		
		public System.Data.Linq.Table<Land> Lands
		{
			get
			{
				return this.GetTable<Land>();
			}
		}
		
		public System.Data.Linq.Table<Street> Streets
		{
			get
			{
				return this.GetTable<Street>();
			}
		}
		
		public System.Data.Linq.Table<Type_Land> Type_Lands
		{
			get
			{
				return this.GetTable<Type_Land>();
			}
		}
		
		public System.Data.Linq.Table<Trouser> Trousers
		{
			get
			{
				return this.GetTable<Trouser>();
			}
		}
		
		public System.Data.Linq.Table<Address_Lan> Address_Lans
		{
			get
			{
				return this.GetTable<Address_Lan>();
			}
		}
		
		public System.Data.Linq.Table<Overview_Land> Overview_Lands
		{
			get
			{
				return this.GetTable<Overview_Land>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Acreage")]
	public partial class Acreage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDAcreage;
		
		private string _Acreage1;
		
		private EntitySet<Land> _Lands;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDAcreageChanging(int value);
    partial void OnIDAcreageChanged();
    partial void OnAcreage1Changing(string value);
    partial void OnAcreage1Changed();
    #endregion
		
		public Acreage()
		{
			this._Lands = new EntitySet<Land>(new Action<Land>(this.attach_Lands), new Action<Land>(this.detach_Lands));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAcreage", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDAcreage
		{
			get
			{
				return this._IDAcreage;
			}
			set
			{
				if ((this._IDAcreage != value))
				{
					this.OnIDAcreageChanging(value);
					this.SendPropertyChanging();
					this._IDAcreage = value;
					this.SendPropertyChanged("IDAcreage");
					this.OnIDAcreageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Acreage", Storage="_Acreage1", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Acreage1
		{
			get
			{
				return this._Acreage1;
			}
			set
			{
				if ((this._Acreage1 != value))
				{
					this.OnAcreage1Changing(value);
					this.SendPropertyChanging();
					this._Acreage1 = value;
					this.SendPropertyChanged("Acreage1");
					this.OnAcreage1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Acreage_Land", Storage="_Lands", ThisKey="IDAcreage", OtherKey="IDAcreage")]
		public EntitySet<Land> Lands
		{
			get
			{
				return this._Lands;
			}
			set
			{
				this._Lands.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lands(Land entity)
		{
			this.SendPropertyChanging();
			entity.Acreage = this;
		}
		
		private void detach_Lands(Land entity)
		{
			this.SendPropertyChanging();
			entity.Acreage = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ward")]
	public partial class Ward : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDWard;
		
		private string _Ward1;
		
		private int _IDTrousers;
		
		private EntitySet<Street> _Streets;
		
		private EntityRef<Trouser> _Trouser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDWardChanging(int value);
    partial void OnIDWardChanged();
    partial void OnWard1Changing(string value);
    partial void OnWard1Changed();
    partial void OnIDTrousersChanging(int value);
    partial void OnIDTrousersChanged();
    #endregion
		
		public Ward()
		{
			this._Streets = new EntitySet<Street>(new Action<Street>(this.attach_Streets), new Action<Street>(this.detach_Streets));
			this._Trouser = default(EntityRef<Trouser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDWard", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDWard
		{
			get
			{
				return this._IDWard;
			}
			set
			{
				if ((this._IDWard != value))
				{
					this.OnIDWardChanging(value);
					this.SendPropertyChanging();
					this._IDWard = value;
					this.SendPropertyChanged("IDWard");
					this.OnIDWardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Ward", Storage="_Ward1", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Ward1
		{
			get
			{
				return this._Ward1;
			}
			set
			{
				if ((this._Ward1 != value))
				{
					this.OnWard1Changing(value);
					this.SendPropertyChanging();
					this._Ward1 = value;
					this.SendPropertyChanged("Ward1");
					this.OnWard1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTrousers", DbType="Int NOT NULL")]
		public int IDTrousers
		{
			get
			{
				return this._IDTrousers;
			}
			set
			{
				if ((this._IDTrousers != value))
				{
					if (this._Trouser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTrousersChanging(value);
					this.SendPropertyChanging();
					this._IDTrousers = value;
					this.SendPropertyChanged("IDTrousers");
					this.OnIDTrousersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ward_Street", Storage="_Streets", ThisKey="IDWard", OtherKey="IDWard")]
		public EntitySet<Street> Streets
		{
			get
			{
				return this._Streets;
			}
			set
			{
				this._Streets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Trouser_Ward", Storage="_Trouser", ThisKey="IDTrousers", OtherKey="IDTrousers", IsForeignKey=true)]
		public Trouser Trouser
		{
			get
			{
				return this._Trouser.Entity;
			}
			set
			{
				Trouser previousValue = this._Trouser.Entity;
				if (((previousValue != value) 
							|| (this._Trouser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Trouser.Entity = null;
						previousValue.Wards.Remove(this);
					}
					this._Trouser.Entity = value;
					if ((value != null))
					{
						value.Wards.Add(this);
						this._IDTrousers = value.IDTrousers;
					}
					else
					{
						this._IDTrousers = default(int);
					}
					this.SendPropertyChanged("Trouser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Streets(Street entity)
		{
			this.SendPropertyChanging();
			entity.Ward = this;
		}
		
		private void detach_Streets(Street entity)
		{
			this.SendPropertyChanging();
			entity.Ward = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Address")]
	public partial class Address : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDAddress;
		
		private string _NumberHouse;
		
		private int _IDStreet;
		
		private EntitySet<Land> _Lands;
		
		private EntityRef<Street> _Street;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDAddressChanging(int value);
    partial void OnIDAddressChanged();
    partial void OnNumberHouseChanging(string value);
    partial void OnNumberHouseChanged();
    partial void OnIDStreetChanging(int value);
    partial void OnIDStreetChanged();
    #endregion
		
		public Address()
		{
			this._Lands = new EntitySet<Land>(new Action<Land>(this.attach_Lands), new Action<Land>(this.detach_Lands));
			this._Street = default(EntityRef<Street>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAddress", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDAddress
		{
			get
			{
				return this._IDAddress;
			}
			set
			{
				if ((this._IDAddress != value))
				{
					this.OnIDAddressChanging(value);
					this.SendPropertyChanging();
					this._IDAddress = value;
					this.SendPropertyChanged("IDAddress");
					this.OnIDAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberHouse", DbType="NVarChar(50)")]
		public string NumberHouse
		{
			get
			{
				return this._NumberHouse;
			}
			set
			{
				if ((this._NumberHouse != value))
				{
					this.OnNumberHouseChanging(value);
					this.SendPropertyChanging();
					this._NumberHouse = value;
					this.SendPropertyChanged("NumberHouse");
					this.OnNumberHouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDStreet", DbType="Int NOT NULL")]
		public int IDStreet
		{
			get
			{
				return this._IDStreet;
			}
			set
			{
				if ((this._IDStreet != value))
				{
					if (this._Street.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDStreetChanging(value);
					this.SendPropertyChanging();
					this._IDStreet = value;
					this.SendPropertyChanged("IDStreet");
					this.OnIDStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Address_Land", Storage="_Lands", ThisKey="IDAddress", OtherKey="IDAddress")]
		public EntitySet<Land> Lands
		{
			get
			{
				return this._Lands;
			}
			set
			{
				this._Lands.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Street_Address", Storage="_Street", ThisKey="IDStreet", OtherKey="IDStreet", IsForeignKey=true)]
		public Street Street
		{
			get
			{
				return this._Street.Entity;
			}
			set
			{
				Street previousValue = this._Street.Entity;
				if (((previousValue != value) 
							|| (this._Street.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Street.Entity = null;
						previousValue.Addresses.Remove(this);
					}
					this._Street.Entity = value;
					if ((value != null))
					{
						value.Addresses.Add(this);
						this._IDStreet = value.IDStreet;
					}
					else
					{
						this._IDStreet = default(int);
					}
					this.SendPropertyChanged("Street");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lands(Land entity)
		{
			this.SendPropertyChanging();
			entity.Address = this;
		}
		
		private void detach_Lands(Land entity)
		{
			this.SendPropertyChanging();
			entity.Address = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _IDCustomer;
		
		private string _CustomerName;
		
		private string _Organization;
		
		private string _Address;
		
		private string _PhoneNumber;
		
		private string _Email;
		
		private string _CMND;
		
		private string _Username;
		
		private string _Pass;
		
		private System.Nullable<bool> _Flag_Active;
		
		private System.Nullable<bool> _Admin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCustomerChanging(System.Guid value);
    partial void OnIDCustomerChanged();
    partial void OnCustomerNameChanging(string value);
    partial void OnCustomerNameChanged();
    partial void OnOrganizationChanging(string value);
    partial void OnOrganizationChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnFlag_ActiveChanging(System.Nullable<bool> value);
    partial void OnFlag_ActiveChanged();
    partial void OnAdminChanging(System.Nullable<bool> value);
    partial void OnAdminChanged();
    #endregion
		
		public Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCustomer", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid IDCustomer
		{
			get
			{
				return this._IDCustomer;
			}
			set
			{
				if ((this._IDCustomer != value))
				{
					this.OnIDCustomerChanging(value);
					this.SendPropertyChanging();
					this._IDCustomer = value;
					this.SendPropertyChanged("IDCustomer");
					this.OnIDCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="NVarChar(30)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this.OnCustomerNameChanging(value);
					this.SendPropertyChanging();
					this._CustomerName = value;
					this.SendPropertyChanged("CustomerName");
					this.OnCustomerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Organization", DbType="NVarChar(30)")]
		public string Organization
		{
			get
			{
				return this._Organization;
			}
			set
			{
				if ((this._Organization != value))
				{
					this.OnOrganizationChanging(value);
					this.SendPropertyChanging();
					this._Organization = value;
					this.SendPropertyChanged("Organization");
					this.OnOrganizationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(15)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(15)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="VarChar(50)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag_Active", DbType="Bit")]
		public System.Nullable<bool> Flag_Active
		{
			get
			{
				return this._Flag_Active;
			}
			set
			{
				if ((this._Flag_Active != value))
				{
					this.OnFlag_ActiveChanging(value);
					this.SendPropertyChanging();
					this._Flag_Active = value;
					this.SendPropertyChanged("Flag_Active");
					this.OnFlag_ActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin", DbType="Bit")]
		public System.Nullable<bool> Admin
		{
			get
			{
				return this._Admin;
			}
			set
			{
				if ((this._Admin != value))
				{
					this.OnAdminChanging(value);
					this.SendPropertyChanging();
					this._Admin = value;
					this.SendPropertyChanged("Admin");
					this.OnAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Follow")]
	public partial class Follow
	{
		
		private System.Guid _IDLand;
		
		private System.Guid _IDCustomer;
		
		public Follow()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLand", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IDLand
		{
			get
			{
				return this._IDLand;
			}
			set
			{
				if ((this._IDLand != value))
				{
					this._IDLand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCustomer", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IDCustomer
		{
			get
			{
				return this._IDCustomer;
			}
			set
			{
				if ((this._IDCustomer != value))
				{
					this._IDCustomer = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Image_Detail")]
	public partial class Image_Detail
	{
		
		private System.Nullable<System.Guid> _IDLand;
		
		private string _Image_detail1;
		
		private string _Title;
		
		public Image_Detail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLand", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> IDLand
		{
			get
			{
				return this._IDLand;
			}
			set
			{
				if ((this._IDLand != value))
				{
					this._IDLand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Image_detail", Storage="_Image_detail1", DbType="VarChar(MAX)")]
		public string Image_detail1
		{
			get
			{
				return this._Image_detail1;
			}
			set
			{
				if ((this._Image_detail1 != value))
				{
					this._Image_detail1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Land")]
	public partial class Land : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _IDLand;
		
		private string _Name;
		
		private string _Decrition;
		
		private System.Nullable<int> _IDAcreage;
		
		private System.Nullable<System.Guid> _IDCustomer;
		
		private System.Nullable<int> _IDType;
		
		private System.Nullable<int> _IDAddress;
		
		private string _Image;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<decimal> _Price;
		
		private string _Decription_mini;
		
		private EntityRef<Acreage> _Acreage;
		
		private EntityRef<Address> _Address;
		
		private EntityRef<Type_Land> _Type_Land;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDLandChanging(System.Guid value);
    partial void OnIDLandChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDecritionChanging(string value);
    partial void OnDecritionChanged();
    partial void OnIDAcreageChanging(System.Nullable<int> value);
    partial void OnIDAcreageChanged();
    partial void OnIDCustomerChanging(System.Nullable<System.Guid> value);
    partial void OnIDCustomerChanged();
    partial void OnIDTypeChanging(System.Nullable<int> value);
    partial void OnIDTypeChanged();
    partial void OnIDAddressChanging(System.Nullable<int> value);
    partial void OnIDAddressChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnDecription_miniChanging(string value);
    partial void OnDecription_miniChanged();
    #endregion
		
		public Land()
		{
			this._Acreage = default(EntityRef<Acreage>);
			this._Address = default(EntityRef<Address>);
			this._Type_Land = default(EntityRef<Type_Land>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLand", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid IDLand
		{
			get
			{
				return this._IDLand;
			}
			set
			{
				if ((this._IDLand != value))
				{
					this.OnIDLandChanging(value);
					this.SendPropertyChanging();
					this._IDLand = value;
					this.SendPropertyChanged("IDLand");
					this.OnIDLandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Decrition", DbType="NVarChar(MAX)")]
		public string Decrition
		{
			get
			{
				return this._Decrition;
			}
			set
			{
				if ((this._Decrition != value))
				{
					this.OnDecritionChanging(value);
					this.SendPropertyChanging();
					this._Decrition = value;
					this.SendPropertyChanged("Decrition");
					this.OnDecritionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAcreage", DbType="Int")]
		public System.Nullable<int> IDAcreage
		{
			get
			{
				return this._IDAcreage;
			}
			set
			{
				if ((this._IDAcreage != value))
				{
					if (this._Acreage.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDAcreageChanging(value);
					this.SendPropertyChanging();
					this._IDAcreage = value;
					this.SendPropertyChanged("IDAcreage");
					this.OnIDAcreageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCustomer", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> IDCustomer
		{
			get
			{
				return this._IDCustomer;
			}
			set
			{
				if ((this._IDCustomer != value))
				{
					this.OnIDCustomerChanging(value);
					this.SendPropertyChanging();
					this._IDCustomer = value;
					this.SendPropertyChanged("IDCustomer");
					this.OnIDCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDType", DbType="Int")]
		public System.Nullable<int> IDType
		{
			get
			{
				return this._IDType;
			}
			set
			{
				if ((this._IDType != value))
				{
					if (this._Type_Land.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTypeChanging(value);
					this.SendPropertyChanging();
					this._IDType = value;
					this.SendPropertyChanged("IDType");
					this.OnIDTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAddress", DbType="Int")]
		public System.Nullable<int> IDAddress
		{
			get
			{
				return this._IDAddress;
			}
			set
			{
				if ((this._IDAddress != value))
				{
					if (this._Address.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDAddressChanging(value);
					this.SendPropertyChanging();
					this._IDAddress = value;
					this.SendPropertyChanged("IDAddress");
					this.OnIDAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarChar(MAX)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Decription_mini", DbType="NVarChar(400)")]
		public string Decription_mini
		{
			get
			{
				return this._Decription_mini;
			}
			set
			{
				if ((this._Decription_mini != value))
				{
					this.OnDecription_miniChanging(value);
					this.SendPropertyChanging();
					this._Decription_mini = value;
					this.SendPropertyChanged("Decription_mini");
					this.OnDecription_miniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Acreage_Land", Storage="_Acreage", ThisKey="IDAcreage", OtherKey="IDAcreage", IsForeignKey=true)]
		public Acreage Acreage
		{
			get
			{
				return this._Acreage.Entity;
			}
			set
			{
				Acreage previousValue = this._Acreage.Entity;
				if (((previousValue != value) 
							|| (this._Acreage.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Acreage.Entity = null;
						previousValue.Lands.Remove(this);
					}
					this._Acreage.Entity = value;
					if ((value != null))
					{
						value.Lands.Add(this);
						this._IDAcreage = value.IDAcreage;
					}
					else
					{
						this._IDAcreage = default(Nullable<int>);
					}
					this.SendPropertyChanged("Acreage");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Address_Land", Storage="_Address", ThisKey="IDAddress", OtherKey="IDAddress", IsForeignKey=true)]
		public Address Address
		{
			get
			{
				return this._Address.Entity;
			}
			set
			{
				Address previousValue = this._Address.Entity;
				if (((previousValue != value) 
							|| (this._Address.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Address.Entity = null;
						previousValue.Lands.Remove(this);
					}
					this._Address.Entity = value;
					if ((value != null))
					{
						value.Lands.Add(this);
						this._IDAddress = value.IDAddress;
					}
					else
					{
						this._IDAddress = default(Nullable<int>);
					}
					this.SendPropertyChanged("Address");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Type_Land_Land", Storage="_Type_Land", ThisKey="IDType", OtherKey="IDType", IsForeignKey=true)]
		public Type_Land Type_Land
		{
			get
			{
				return this._Type_Land.Entity;
			}
			set
			{
				Type_Land previousValue = this._Type_Land.Entity;
				if (((previousValue != value) 
							|| (this._Type_Land.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Type_Land.Entity = null;
						previousValue.Lands.Remove(this);
					}
					this._Type_Land.Entity = value;
					if ((value != null))
					{
						value.Lands.Add(this);
						this._IDType = value.IDType;
					}
					else
					{
						this._IDType = default(Nullable<int>);
					}
					this.SendPropertyChanged("Type_Land");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Street")]
	public partial class Street : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDStreet;
		
		private string _Street1;
		
		private int _IDWard;
		
		private EntitySet<Address> _Addresses;
		
		private EntityRef<Ward> _Ward;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDStreetChanging(int value);
    partial void OnIDStreetChanged();
    partial void OnStreet1Changing(string value);
    partial void OnStreet1Changed();
    partial void OnIDWardChanging(int value);
    partial void OnIDWardChanged();
    #endregion
		
		public Street()
		{
			this._Addresses = new EntitySet<Address>(new Action<Address>(this.attach_Addresses), new Action<Address>(this.detach_Addresses));
			this._Ward = default(EntityRef<Ward>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDStreet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDStreet
		{
			get
			{
				return this._IDStreet;
			}
			set
			{
				if ((this._IDStreet != value))
				{
					this.OnIDStreetChanging(value);
					this.SendPropertyChanging();
					this._IDStreet = value;
					this.SendPropertyChanged("IDStreet");
					this.OnIDStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Street", Storage="_Street1", DbType="NVarChar(50)")]
		public string Street1
		{
			get
			{
				return this._Street1;
			}
			set
			{
				if ((this._Street1 != value))
				{
					this.OnStreet1Changing(value);
					this.SendPropertyChanging();
					this._Street1 = value;
					this.SendPropertyChanged("Street1");
					this.OnStreet1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDWard", DbType="Int NOT NULL")]
		public int IDWard
		{
			get
			{
				return this._IDWard;
			}
			set
			{
				if ((this._IDWard != value))
				{
					if (this._Ward.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDWardChanging(value);
					this.SendPropertyChanging();
					this._IDWard = value;
					this.SendPropertyChanged("IDWard");
					this.OnIDWardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Street_Address", Storage="_Addresses", ThisKey="IDStreet", OtherKey="IDStreet")]
		public EntitySet<Address> Addresses
		{
			get
			{
				return this._Addresses;
			}
			set
			{
				this._Addresses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ward_Street", Storage="_Ward", ThisKey="IDWard", OtherKey="IDWard", IsForeignKey=true)]
		public Ward Ward
		{
			get
			{
				return this._Ward.Entity;
			}
			set
			{
				Ward previousValue = this._Ward.Entity;
				if (((previousValue != value) 
							|| (this._Ward.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ward.Entity = null;
						previousValue.Streets.Remove(this);
					}
					this._Ward.Entity = value;
					if ((value != null))
					{
						value.Streets.Add(this);
						this._IDWard = value.IDWard;
					}
					else
					{
						this._IDWard = default(int);
					}
					this.SendPropertyChanged("Ward");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Addresses(Address entity)
		{
			this.SendPropertyChanging();
			entity.Street = this;
		}
		
		private void detach_Addresses(Address entity)
		{
			this.SendPropertyChanging();
			entity.Street = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Type_Land")]
	public partial class Type_Land : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDType;
		
		private string _TypeName;
		
		private EntitySet<Land> _Lands;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTypeChanging(int value);
    partial void OnIDTypeChanged();
    partial void OnTypeNameChanging(string value);
    partial void OnTypeNameChanged();
    #endregion
		
		public Type_Land()
		{
			this._Lands = new EntitySet<Land>(new Action<Land>(this.attach_Lands), new Action<Land>(this.detach_Lands));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDType", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDType
		{
			get
			{
				return this._IDType;
			}
			set
			{
				if ((this._IDType != value))
				{
					this.OnIDTypeChanging(value);
					this.SendPropertyChanging();
					this._IDType = value;
					this.SendPropertyChanged("IDType");
					this.OnIDTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TypeName
		{
			get
			{
				return this._TypeName;
			}
			set
			{
				if ((this._TypeName != value))
				{
					this.OnTypeNameChanging(value);
					this.SendPropertyChanging();
					this._TypeName = value;
					this.SendPropertyChanged("TypeName");
					this.OnTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Type_Land_Land", Storage="_Lands", ThisKey="IDType", OtherKey="IDType")]
		public EntitySet<Land> Lands
		{
			get
			{
				return this._Lands;
			}
			set
			{
				this._Lands.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lands(Land entity)
		{
			this.SendPropertyChanging();
			entity.Type_Land = this;
		}
		
		private void detach_Lands(Land entity)
		{
			this.SendPropertyChanging();
			entity.Type_Land = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Trousers")]
	public partial class Trouser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTrousers;
		
		private string _Trousers;
		
		private EntitySet<Ward> _Wards;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTrousersChanging(int value);
    partial void OnIDTrousersChanged();
    partial void OnTrousersChanging(string value);
    partial void OnTrousersChanged();
    #endregion
		
		public Trouser()
		{
			this._Wards = new EntitySet<Ward>(new Action<Ward>(this.attach_Wards), new Action<Ward>(this.detach_Wards));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTrousers", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDTrousers
		{
			get
			{
				return this._IDTrousers;
			}
			set
			{
				if ((this._IDTrousers != value))
				{
					this.OnIDTrousersChanging(value);
					this.SendPropertyChanging();
					this._IDTrousers = value;
					this.SendPropertyChanged("IDTrousers");
					this.OnIDTrousersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trousers", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Trousers
		{
			get
			{
				return this._Trousers;
			}
			set
			{
				if ((this._Trousers != value))
				{
					this.OnTrousersChanging(value);
					this.SendPropertyChanging();
					this._Trousers = value;
					this.SendPropertyChanged("Trousers");
					this.OnTrousersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Trouser_Ward", Storage="_Wards", ThisKey="IDTrousers", OtherKey="IDTrousers")]
		public EntitySet<Ward> Wards
		{
			get
			{
				return this._Wards;
			}
			set
			{
				this._Wards.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Wards(Ward entity)
		{
			this.SendPropertyChanging();
			entity.Trouser = this;
		}
		
		private void detach_Wards(Ward entity)
		{
			this.SendPropertyChanging();
			entity.Trouser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Address_Lan")]
	public partial class Address_Lan
	{
		
		private System.Guid _IDLand;
		
		private string _Name;
		
		private string _Street;
		
		private string _Ward;
		
		private string _Trousers;
		
		private string _NumberHouse;
		
		private int _IDStreet;
		
		private int _IDWard;
		
		private int _IDTrousers;
		
		public Address_Lan()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLand", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IDLand
		{
			get
			{
				return this._IDLand;
			}
			set
			{
				if ((this._IDLand != value))
				{
					this._IDLand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="NVarChar(50)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this._Street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ward", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Ward
		{
			get
			{
				return this._Ward;
			}
			set
			{
				if ((this._Ward != value))
				{
					this._Ward = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trousers", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Trousers
		{
			get
			{
				return this._Trousers;
			}
			set
			{
				if ((this._Trousers != value))
				{
					this._Trousers = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberHouse", DbType="NVarChar(50)")]
		public string NumberHouse
		{
			get
			{
				return this._NumberHouse;
			}
			set
			{
				if ((this._NumberHouse != value))
				{
					this._NumberHouse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDStreet", DbType="Int NOT NULL")]
		public int IDStreet
		{
			get
			{
				return this._IDStreet;
			}
			set
			{
				if ((this._IDStreet != value))
				{
					this._IDStreet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDWard", DbType="Int NOT NULL")]
		public int IDWard
		{
			get
			{
				return this._IDWard;
			}
			set
			{
				if ((this._IDWard != value))
				{
					this._IDWard = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTrousers", DbType="Int NOT NULL")]
		public int IDTrousers
		{
			get
			{
				return this._IDTrousers;
			}
			set
			{
				if ((this._IDTrousers != value))
				{
					this._IDTrousers = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Overview_Land")]
	public partial class Overview_Land
	{
		
		private System.Guid _IDLand;
		
		private string _Name;
		
		private string _Image;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<decimal> _Price;
		
		private string _Decription_mini;
		
		private string _Acreage;
		
		private string _TypeName;
		
		private string _Street;
		
		private string _Ward;
		
		private string _Trousers;
		
		private string _NumberHouse;
		
		private int _IDStreet;
		
		private int _IDWard;
		
		private int _IDTrousers;
		
		private int _IDType;
		
		private int _IDAcreage;
		
		public Overview_Land()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLand", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IDLand
		{
			get
			{
				return this._IDLand;
			}
			set
			{
				if ((this._IDLand != value))
				{
					this._IDLand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarChar(MAX)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Decription_mini", DbType="NVarChar(400)")]
		public string Decription_mini
		{
			get
			{
				return this._Decription_mini;
			}
			set
			{
				if ((this._Decription_mini != value))
				{
					this._Decription_mini = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acreage", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Acreage
		{
			get
			{
				return this._Acreage;
			}
			set
			{
				if ((this._Acreage != value))
				{
					this._Acreage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TypeName
		{
			get
			{
				return this._TypeName;
			}
			set
			{
				if ((this._TypeName != value))
				{
					this._TypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="NVarChar(50)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this._Street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ward", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Ward
		{
			get
			{
				return this._Ward;
			}
			set
			{
				if ((this._Ward != value))
				{
					this._Ward = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trousers", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Trousers
		{
			get
			{
				return this._Trousers;
			}
			set
			{
				if ((this._Trousers != value))
				{
					this._Trousers = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberHouse", DbType="NVarChar(50)")]
		public string NumberHouse
		{
			get
			{
				return this._NumberHouse;
			}
			set
			{
				if ((this._NumberHouse != value))
				{
					this._NumberHouse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDStreet", DbType="Int NOT NULL")]
		public int IDStreet
		{
			get
			{
				return this._IDStreet;
			}
			set
			{
				if ((this._IDStreet != value))
				{
					this._IDStreet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDWard", DbType="Int NOT NULL")]
		public int IDWard
		{
			get
			{
				return this._IDWard;
			}
			set
			{
				if ((this._IDWard != value))
				{
					this._IDWard = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTrousers", DbType="Int NOT NULL")]
		public int IDTrousers
		{
			get
			{
				return this._IDTrousers;
			}
			set
			{
				if ((this._IDTrousers != value))
				{
					this._IDTrousers = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDType", DbType="Int NOT NULL")]
		public int IDType
		{
			get
			{
				return this._IDType;
			}
			set
			{
				if ((this._IDType != value))
				{
					this._IDType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAcreage", DbType="Int NOT NULL")]
		public int IDAcreage
		{
			get
			{
				return this._IDAcreage;
			}
			set
			{
				if ((this._IDAcreage != value))
				{
					this._IDAcreage = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
